<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

| Term       | Brief Description                        |
|------------|------------------------------------------|
| Subsetting | Selecting a subset                       |
| Indexing   | Selecting 1 element                      | 
| Slicing    | Selecting a range of elements            |
| Masking    | Selecting elements using a boolean array |

In [16]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[np_array_2d[:, 0].astype(int) % 2 == 1, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [28]:
arr = np.array([[66, 50, 57, -1, -1],
                [92, -1, 88, -1, -1],
                [75, -1, -1, 76, -1],
                [-1, 51, 87, -1, -1],
                [71, -1, 67, -1, 69]])
arr[arr < 50] = -1
arr[arr == 50] = 0
arr[arr > 50] = 1
print(arr)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
